### ISSUE TITLE
Add compiled binaries to releases

### ISSUE THREAD

**Issue by leha-code** [MCPI-Revival/TextureWeaving#1]

**Comment by torralbaa** [comment]
I think either something like this, or adding a Makefile, for people who don't have/don't want to install Gradle.

**Comment by TheBrokenRail** [comment]
> I think either something like this, or adding a Makefile, for people who don't have/don't want to install Gradle.

Any ``Makefile`` would still need Gradle unless you made your own Java build system. Anyways ``gradlew`` downloads it for you, just run ``./gradlew build`` (make sure Java is installed).

**Comment by torralbaa** [comment]
I mean you could do something like
```makefile
JCFLAGS:=# ...

all:
    javac $(JCFLAGS) ./path/to/files*/*.java
    # ...
    jar -cfm Manifest.txt ./path/to/files*/*.class
    # ...
```

Since Gradle is _chonky_, but it's up to you anyways.

**Comment by NoozAbooz** [comment]
I'll just add install instructions.
